### ISSUE TITLE
Issue with Hashnode User Profile Button Referencing Old Username

### ISSUE THREAD

**Issue by s-soumyakanta** [Hashnode/starter-kit#58]
Greetings,

I hope this message finds you well. I wanted to bring a minor concern to your attention regarding the Hashnode profile button in the UI of packages/blog-starter-kit/themes/enterprise. 

It has come to my notice that the button continues to reference my old username, "ssoumyakanta" despite it being updated quite some time ago. My current username is "s-soumyakanta" 
![hashnode url](https://github.com/Hashnode/starter-kit/assets/92138792/8ef4d914-557a-4cef-b6a2-005142411f5d)
![Screenshot (90)](https://github.com/Hashnode/starter-kit/assets/92138792/9e96c0b4-64ae-4598-bedc-e3adaea402db)
![Screenshot (91)](https://github.com/Hashnode/starter-kit/assets/92138792/5aadf265-d085-4c7e-83db-7bd468dc9a07)

Thanks for the awesome Headless Hashnode Starter Kit themes! It's been a great experience.
 
Best regards
S Soumyakanta

**Comment by panda-sandeep** [comment]
Hi thanks for flagging this! We're taking a look.

**Comment by panda-sandeep** [comment]
@s-soumyakanta We looked into it. Initially, when a user signs up by entering the username, we also update the Hashnode link in the publication dashboard automatically. After signup, we allow the username to be changed once. If the user then updates their username, we don't update the Hashnode link in the publication. We'll look into it separately because it's a different issue. For now, my suggestion is to update it in the dashboard (which is what you have done already).
